/**
 * Self-hosts the two brand typefaces (SIL Open Font License) so the site makes
 * no third-party requests. Only the latin + latin-ext subsets are kept.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'public/fonts');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const URL = 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300&family=Jost:wght@300;400&display=swap';

const KEEP = new Set(['latin', 'latin-ext']);
const subsetName = (range) =>
  range.includes('U+0000-00FF') ? 'latin' : range.includes('U+0100-02BA') ? 'latin-ext' : 'other';

await mkdir(OUT, { recursive: true });
const css = await (await fetch(URL, { headers: { 'User-Agent': UA } })).text();

const faces = [...css.matchAll(/\/\*[^*]*\*\/\s*@font-face\s*\{([^}]+)\}/g)].map((m) => m[1]);
const downloaded = new Map(); // remote url -> local filename (Google serves one variable file per family)
const out = [];
for (const body of faces) {
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const style = /font-style:\s*(\w+)/.exec(body)[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)[1];
  const url = /src:\s*url\(([^)]+)\)/.exec(body)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();
  const subset = subsetName(range);
  if (!KEEP.has(subset)) continue;

  let slug = downloaded.get(url);
  if (!slug) {
    slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(path.join(OUT, slug), buf);
    downloaded.set(url, slug);
    console.log(`${slug}  ${(buf.length / 1024).toFixed(1)} KB`);
  }
  out.push(
    `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url('/fonts/${slug}') format('woff2');\n  unicode-range: ${range};\n}`,
  );
}

await writeFile(
  path.join(ROOT, 'src/styles/fonts.css'),
  `/* Cormorant Garamond & Jost — SIL Open Font License 1.1. Generated by scripts/fetch-fonts.mjs. */\n\n${out.join('\n\n')}\n`,
);
console.log(`\n${out.length} faces -> src/styles/fonts.css`);
